### ISSUE TITLE
No clue how to make the file

### ISSUE THREAD

**Issue by machinalupus** [mwpenny/portal64-still-alive#90]
I have no clue how to build the rom so any help would be nice. I am more than willing to play test. So excited for version 16.

**Comment by hackgrid** [comment]
Follow the readme

**Comment by mwpenny** [comment]
@machinalupus glad to hear you're excited about it. What steps have you tried?

**Comment by machinalupus** [comment]
Honestly I need the 101 class on how to do GitHub projects. Also can it be done on phone or do the builds have to be made on computer?

Yahoo Mail: Search, Organize, Conquer 
 
  On Sun, Sep 8, 2024 at 9:19 AM, Matt ***@***.***> wrote:   


@machinalupus glad to hear you're excited about it. What steps have you tried?

**Comment by mwpenny** [comment]
Is it possible on a phone? _Theoretically_ I'm sure it is with the right setup, but that's not something we support and it would probably be a headache anyway.

You'll need either a Linux machine (or virtual machine or Windows Subsystem for Linux) or use Docker. Instructions are written assuming Ubuntu Linux. It's possible to use other operating systems, but you'll have to get that set up yourself if you decide to go that way (Docker makes it easier).

In my opinion Docker is probably easiest for newcomers since you only need to set up the one dependency and everything is self contained. But if you use Ubuntu then the setup script is pretty straightforward too and will do everything for you. You have options depending on your preferences.

The readme has all of this under the "how to build" section. We assume some familiarity with compiling software (git, make, etc.) and limit the scope of the docs to this project. Since you're new to this, checking out some git and make documentation / tutorials online would help provise a basis.

**Comment by hackgrid** [comment]
Currently you can only build on systems with an x86/x64 processor - even emulation or Docker does not work because of 

https://projects.blender.org/blender/blender/issues/118702

But i looks like they upgraded to USD 24.05 with Blender 4.2, so it could work in the future if portal64 supports higher Blender versions again.

You could check out

https://www.youtube.com/watch?v=DOQUGQgoxKM

**Comment by machinalupus** [comment]
I am computerless at the moment sadly.

Yahoo Mail: Search, Organize, Conquer 
 
  On Sun, Sep 8, 2024 at 2:41 PM, ***@***.***> wrote:   


Currently you can only build on systems with an x86/x64 processor - even emulation or Docker does not work because of

https://projects.blender.org/blender/blender/issues/118702

But i looks like they upgraded to USD 24.05 with Blender 4.2, so it could work in the future if portal64 supports higher Blender versions again.

You could check out

https://www.youtube.com/watch?v=DOQUGQgoxKM

**Comment by machinalupus** [comment]
Thank you so much and keep up the amazing work.

Yahoo Mail: Search, Organize, Conquer 
 
  On Sun, Sep 8, 2024 at 2:54 PM, Josh ***@***.***> wrote:   I am computerless at the moment sadly.

Yahoo Mail: Search, Organize, Conquer 
 
  On Sun, Sep 8, 2024 at 2:41 PM, ***@***.***> wrote:   


Currently you can only build on systems with an x86/x64 processor - even emulation or Docker does not work because of

https://projects.blender.org/blender/blender/issues/118702

But i looks like they upgraded to USD 24.05 with Blender 4.2, so it could work in the future if portal64 supports higher Blender versions again.

You could check out

https://www.youtube.com/watch?v=DOQUGQgoxKM

**Comment by mwpenny** [comment]
@hackgrid good to know, thanks! Another reason to upgrade Blender.

@machinalupus sorry to hear that. I'll close this issue. One day we hope to be able to distribute ROMs again (to those who legally own the original Portal).
